package com.restaurantes.ui.ide;// Generated by Selenium IDE

import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Before;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
public class RestaurantListIDETest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void list2() {
        driver.get("http://localhost:8080/restaurants");
        driver.findElement(By.linkText("Ver")).click();
        driver.findElement(By.cssSelector(".justify-content-between")).click();
        driver.findElement(By.linkText("Ver")).click();
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        driver.findElement(By.id("loginLink")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("user");
        driver.findElement(By.id("password")).sendKeys("user");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Ver")).click();
        driver.findElement(By.linkText("Hacer pedido")).click();
        driver.findElement(By.id("tableNumber")).click();
        driver.findElement(By.id("tableNumber")).sendKeys("1");
        driver.findElement(By.id("numPeople")).sendKeys("1");
        driver.findElement(By.id("userSuggestions")).sendKeys("1");
        driver.findElement(By.cssSelector(".btn-success")).click();
    }
}
